version: "3.9"
   
services:
  db:
    image: postgres
    ports:
      - "5435:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env.dev
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db